export const ADD_BLOG_ENTRY = 'ADD_BLOG_ENTRY';
export const FETCH_BLOG_ENTRIES = 'FETCH_BLOG_ENTRIES';
export const DELETE_BLOG_ENTRY = 'DELETE_BLOG_ENTRY';
export const UPDATE_BLOG_ENTRY = 'UPDATE_BLOG_ENTRY';